name: Package Application - Windows

on: 
  workflow_dispatch:
  push:

jobs:
  win-build:
    name: build Windows

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
      
    - name: Git checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: git
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements-nightly.txt
    
    - name: pyinstaller build
      run: |
        python build.py

    - name: Move files
      shell: pwsh
      run: ;
        mv ./dist ./wme-Windows

    - uses: actions/upload-artifact@v4
      with:
        name: "wme-windows-2.4.0 - ${{github.run_number}}"
        path: ./wme-Windows
