name: Package Application - Windows

on: workflow_dispatch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  win-build:
    name: build Windows

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
      
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: pyinstaller build
      run: |
        python build.py

    - name: Create zip
      shell: pwsh
      run: ;
        mv ./dist ./wme-Windows ;
        Compress-Archive ./wme-Windows/ ./wme-Windows.zip ;

    - uses: actions/upload-artifact@v2
      with:
        name: wme
        path: ./wme-Windows.zip
