name: Package Application with Pyinstaller

on: workflow_dispatch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git --version
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git status
        git tag
        git describe
    
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        spec: build.py
        requirements: requirements.txt
        path: ./

    - uses: actions/upload-artifact@v2
      with:
        name: wme
        path: dist/windows
